import { generateWords } from "./generateWords";

test("generateWords returns a unique list of 25 words, turn passed to determine starting count", () => {
  expect(
    generateWords(
      [
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "g" },
        { word_id: 0, word: "sd" },
        { word_id: 0, word: "sdsa" },
        { word_id: 0, word: "sadsad" },
        { word_id: 0, word: "sdasad" },
        { word_id: 0, word: "sadasdsad" },
        { word_id: 0, word: "sadsdasdasd" },
        { word_id: 0, word: "afasda" },
        { word_id: 0, word: "efwe" },
        { word_id: 0, word: "dsaqw" },
        { word_id: 0, word: "dwqqw" },
        { word_id: 0, word: "wdqwqw" },
        { word_id: 0, word: "gfsgs" },
        { word_id: 0, word: "dwqdwq" },
        { word_id: 0, word: "fdsfdsfs" },
        { word_id: 0, word: "fdsd" },
        { word_id: 0, word: "dqwde" },
        { word_id: 0, word: "dsdasds" },
        { word_id: 0, word: "32fwsdca" },
      ],
      false
    ).length
  ).toEqual(25);
  expect(
    generateWords(
      [
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "g" },
        { word_id: 0, word: "sd" },
        { word_id: 0, word: "sdsa" },
        { word_id: 0, word: "sadsad" },
        { word_id: 0, word: "sdasad" },
        { word_id: 0, word: "sadasdsad" },
        { word_id: 0, word: "sadsdasdasd" },
        { word_id: 0, word: "afasda" },
        { word_id: 0, word: "efwe" },
        { word_id: 0, word: "dsaqw" },
        { word_id: 0, word: "dwqqw" },
        { word_id: 0, word: "wdqwqw" },
        { word_id: 0, word: "gfsgs" },
        { word_id: 0, word: "dwqdwq" },
        { word_id: 0, word: "fdsfdsfs" },
        { word_id: 0, word: "fdsd" },
        { word_id: 0, word: "dqwde" },
        { word_id: 0, word: "dsdasds" },
        { word_id: 0, word: "32fwsdca" },
      ],
      true
    ).length
  ).toEqual(25);
  expect(
    generateWords(
      [
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "g" },
        { word_id: 0, word: "sd" },
        { word_id: 0, word: "sdsa" },
        { word_id: 0, word: "sadsad" },
        { word_id: 0, word: "sdasad" },
        { word_id: 0, word: "sadasdsad" },
        { word_id: 0, word: "sadsdasdasd" },
        { word_id: 0, word: "afasda" },
        { word_id: 0, word: "efwe" },
        { word_id: 0, word: "dsaqw" },
        { word_id: 0, word: "dwqqw" },
        { word_id: 0, word: "wdqwqw" },
        { word_id: 0, word: "gfsgs" },
        { word_id: 0, word: "dwqdwq" },
        { word_id: 0, word: "fdsfdsfs" },
        { word_id: 0, word: "fdsd" },
        { word_id: 0, word: "dqwde" },
        { word_id: 0, word: "dsdasds" },
        { word_id: 0, word: "32fwsdca" },
      ],
      false
    ).filter((element) => element.color === "red").length
  ).toEqual(9);
  expect(
    generateWords(
      [
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "g" },
        { word_id: 0, word: "sd" },
        { word_id: 0, word: "sdsa" },
        { word_id: 0, word: "sadsad" },
        { word_id: 0, word: "sdasad" },
        { word_id: 0, word: "sadasdsad" },
        { word_id: 0, word: "sadsdasdasd" },
        { word_id: 0, word: "afasda" },
        { word_id: 0, word: "efwe" },
        { word_id: 0, word: "dsaqw" },
        { word_id: 0, word: "dwqqw" },
        { word_id: 0, word: "wdqwqw" },
        { word_id: 0, word: "gfsgs" },
        { word_id: 0, word: "dwqdwq" },
        { word_id: 0, word: "fdsfdsfs" },
        { word_id: 0, word: "fdsd" },
        { word_id: 0, word: "dqwde" },
        { word_id: 0, word: "dsdasds" },
        { word_id: 0, word: "32fwsdca" },
      ],
      false
    ).filter((element) => element.color === "blue").length
  ).toEqual(8);
  expect(
    generateWords(
      [
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "g" },
        { word_id: 0, word: "sd" },
        { word_id: 0, word: "sdsa" },
        { word_id: 0, word: "sadsad" },
        { word_id: 0, word: "sdasad" },
        { word_id: 0, word: "sadasdsad" },
        { word_id: 0, word: "sadsdasdasd" },
        { word_id: 0, word: "afasda" },
        { word_id: 0, word: "efwe" },
        { word_id: 0, word: "dsaqw" },
        { word_id: 0, word: "dwqqw" },
        { word_id: 0, word: "wdqwqw" },
        { word_id: 0, word: "gfsgs" },
        { word_id: 0, word: "dwqdwq" },
        { word_id: 0, word: "fdsfdsfs" },
        { word_id: 0, word: "fdsd" },
        { word_id: 0, word: "dqwde" },
        { word_id: 0, word: "dsdasds" },
        { word_id: 0, word: "32fwsdca" },
      ],
      true
    ).filter((element) => element.color === "red").length
  ).toEqual(8);
  expect(
    generateWords(
      [
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "a" },
        { word_id: 0, word: "b" },
        { word_id: 0, word: "c" },
        { word_id: 0, word: "d" },
        { word_id: 0, word: "e" },
        { word_id: 0, word: "f" },
        { word_id: 0, word: "g" },
        { word_id: 0, word: "sd" },
        { word_id: 0, word: "sdsa" },
        { word_id: 0, word: "sadsad" },
        { word_id: 0, word: "sdasad" },
        { word_id: 0, word: "sadasdsad" },
        { word_id: 0, word: "sadsdasdasd" },
        { word_id: 0, word: "afasda" },
        { word_id: 0, word: "efwe" },
        { word_id: 0, word: "dsaqw" },
        { word_id: 0, word: "dwqqw" },
        { word_id: 0, word: "wdqwqw" },
        { word_id: 0, word: "gfsgs" },
        { word_id: 0, word: "dwqdwq" },
        { word_id: 0, word: "fdsfdsfs" },
        { word_id: 0, word: "fdsd" },
        { word_id: 0, word: "dqwde" },
        { word_id: 0, word: "dsdasds" },
        { word_id: 0, word: "32fwsdca" },
      ],
      true
    ).filter((element) => element.color === "blue").length
  ).toEqual(9);
});
