import { Color } from "../types/Color";
import { shuffle } from "./shuffle";

test("shuffle returns a random order of the orignal list", () => {
  expect(
    shuffle([
      { word: "a", color: Color.Black, ishidden: false },
      { word: "b", color: Color.Black, ishidden: false },
      { word: "c", color: Color.Black, ishidden: false },
      { word: "d", color: Color.Black, ishidden: false },
      { word: "e", color: Color.Black, ishidden: false },
      { word: "f", color: Color.Black, ishidden: false },
      { word: "a", color: Color.Black, ishidden: false },
      { word: "b", color: Color.Black, ishidden: false },
      { word: "c", color: Color.Black, ishidden: false },
      { word: "d", color: Color.Black, ishidden: false },
      { word: "e", color: Color.Black, ishidden: false },
      { word: "f", color: Color.Black, ishidden: false },
      { word: "a", color: Color.Black, ishidden: false },
      { word: "b", color: Color.Black, ishidden: false },
      { word: "c", color: Color.Black, ishidden: false },
      { word: "d", color: Color.Black, ishidden: false },
      { word: "e", color: Color.Black, ishidden: false },
      { word: "f", color: Color.Black, ishidden: false },
      { word: "a", color: Color.Black, ishidden: false },
      { word: "b", color: Color.Black, ishidden: false },
      { word: "c", color: Color.Black, ishidden: false },
      { word: "d", color: Color.Black, ishidden: false },
      { word: "e", color: Color.Black, ishidden: false },
      { word: "f", color: Color.Black, ishidden: false },
      { word: "g", color: Color.Black, ishidden: false },
      { word: "sd", color: Color.Black, ishidden: false },
      { word: "sdsa", color: Color.Black, ishidden: false },
      { word: "sadsad", color: Color.Black, ishidden: false },
      { word: "sdasdasd", color: Color.Black, ishidden: false },
      { word: "sadasdsad", color: Color.Black, ishidden: false },
      { word: "sadsdasdasd", color: Color.Black, ishidden: false },
      { word: "afasda", color: Color.Black, ishidden: false },
      { word: "efwe", color: Color.Black, ishidden: false },
      { word: "dsaqw", color: Color.Black, ishidden: false },
      { word: "dwqqw", color: Color.Black, ishidden: false },
      { word: "wdqwqw", color: Color.Black, ishidden: false },
      { word: "gfsgs", color: Color.Black, ishidden: false },
      { word: "dwqdwq", color: Color.Black, ishidden: false },
      { word: "fdsfdsfs", color: Color.Black, ishidden: false },
      { word: "fdsd", color: Color.Black, ishidden: false },
      { word: "dqwde", color: Color.Black, ishidden: false },
      { word: "dsdasds", color: Color.Black, ishidden: false },
      { word: "32fwsdca", color: Color.Black, ishidden: false },
    ]).length
  ).toEqual(43);
});
