import { shuffle } from "./shuffle";

test("shuffle returns a random order of the orignal list", () => {
  expect(
    shuffle([
      ["a", "black"],
      ["b", "black"],
      ["c", "black"],
      ["d", "black"],
      ["e", "black"],
      ["f", "black"],
      ["a", "black"],
      ["b", "black"],
      ["c", "black"],
      ["d", "black"],
      ["e", "black"],
      ["f", "black"],
      ["a", "black"],
      ["b", "black"],
      ["c", "black"],
      ["d", "black"],
      ["e", "black"],
      ["f", "black"],
      ["a", "black"],
      ["b", "black"],
      ["c", "black"],
      ["d", "black"],
      ["e", "black"],
      ["f", "black"],
      ["g", "black"],
      ["sd", "black"],
      ["sdsa", "black"],
      ["sadsad", "black"],
      ["sdasdasd", "black"],
      ["sadasdsad", "black"],
      ["sadsdasdasd", "black"],
      ["afasda", "black"],
      ["efwe", "black"],
      ["dsaqw", "black"],
      ["dwqqw", "black"],
      ["wdqwqw", "black"],
      ["gfsgs", "black"],
      ["dwqdwq", "black"],
      ["fdsfdsfs", "black"],
      ["fdsd", "black"],
      ["dqwde", "black"],
      ["dsdasds", "black"],
      ["32fwsdca", "black"],
    ]).length
  ).toEqual(43);
});
