import { shuffle } from "./shuffle";

test("shuffle returns a random order of the orignal list", () => {
  expect(
    shuffle([
      { word: "a", color: "black", ishidden: false },
      { word: "b", color: "black", ishidden: false },
      { word: "c", color: "black", ishidden: false },
      { word: "d", color: "black", ishidden: false },
      { word: "e", color: "black", ishidden: false },
      { word: "f", color: "black", ishidden: false },
      { word: "a", color: "black", ishidden: false },
      { word: "b", color: "black", ishidden: false },
      { word: "c", color: "black", ishidden: false },
      { word: "d", color: "black", ishidden: false },
      { word: "e", color: "black", ishidden: false },
      { word: "f", color: "black", ishidden: false },
      { word: "a", color: "black", ishidden: false },
      { word: "b", color: "black", ishidden: false },
      { word: "c", color: "black", ishidden: false },
      { word: "d", color: "black", ishidden: false },
      { word: "e", color: "black", ishidden: false },
      { word: "f", color: "black", ishidden: false },
      { word: "a", color: "black", ishidden: false },
      { word: "b", color: "black", ishidden: false },
      { word: "c", color: "black", ishidden: false },
      { word: "d", color: "black", ishidden: false },
      { word: "e", color: "black", ishidden: false },
      { word: "f", color: "black", ishidden: false },
      { word: "g", color: "black", ishidden: false },
      { word: "sd", color: "black", ishidden: false },
      { word: "sdsa", color: "black", ishidden: false },
      { word: "sadsad", color: "black", ishidden: false },
      { word: "sdasdasd", color: "black", ishidden: false },
      { word: "sadasdsad", color: "black", ishidden: false },
      { word: "sadsdasdasd", color: "black", ishidden: false },
      { word: "afasda", color: "black", ishidden: false },
      { word: "efwe", color: "black", ishidden: false },
      { word: "dsaqw", color: "black", ishidden: false },
      { word: "dwqqw", color: "black", ishidden: false },
      { word: "wdqwqw", color: "black", ishidden: false },
      { word: "gfsgs", color: "black", ishidden: false },
      { word: "dwqdwq", color: "black", ishidden: false },
      { word: "fdsfdsfs", color: "black", ishidden: false },
      { word: "fdsd", color: "black", ishidden: false },
      { word: "dqwde", color: "black", ishidden: false },
      { word: "dsdasds", color: "black", ishidden: false },
      { word: "32fwsdca", color: "black", ishidden: false },
    ]).length
  ).toEqual(43);
});
